[masters]
k8s-control-plane-01 ansible_host=10.10.99.31

[workers]
k8s-worker-01 ansible_host=10.10.99.32
k8s-worker-02 ansible_host=10.10.99.33

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
ansible_user=secops
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
